//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UD2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string DonViTinh { get; set; }
        public decimal DonGia { get; set; }
        public string MaLoaiMatHang { get; set; }
    
        public virtual LoaiMatHang LoaiMatHang { get; set; }
    }
}
